import { Agent } from './agents';

/** Static demo roster for onboarding slides only — not used in the live app. */
export const DEMO_AGENTS: Agent[] = [
  {
    id: 'maya',
    name: 'Maya',
    role: 'Research Lead',
    emblem: 'triStack',
    gradKey: 'aa',
    status: 'online',
    activity: 'Synthesizing market signals',
    origin: 'Telegram',
    importedAt: 'Mar 14',
    avatarUrl: null,
    bio: 'Sharp, methodical, allergic to hand-wavy claims.',
    stats: { convos: 412, accuracy: 96, hours: 38 },
    memory: ['Prefers primary sources over secondary blogs.'],
  },
  {
    id: 'finn',
    name: 'Finn',
    role: 'Code Architect',
    emblem: 'hexMesh',
    gradKey: 'bb',
    status: 'online',
    activity: 'Refactoring auth flow',
    origin: 'Claude',
    importedAt: 'Mar 14',
    avatarUrl: null,
    bio: 'Loves a clean diff.',
    stats: { convos: 287, accuracy: 94, hours: 41 },
    memory: ['Stack: React Native + Expo.'],
  },
  {
    id: 'iris',
    name: 'Iris',
    role: 'Brand Voice',
    emblem: 'spark',
    gradKey: 'cc',
    status: 'away',
    activity: 'Drafting launch copy',
    origin: 'ChatGPT',
    importedAt: 'Mar 12',
    avatarUrl: null,
    bio: 'Writes like she edits — ruthless.',
    stats: { convos: 198, accuracy: 92, hours: 22 },
    memory: ['Your voice: warm-direct, no startup-speak.'],
  },
  {
    id: 'kai',
    name: 'Kai',
    role: 'Ops Coordinator',
    emblem: 'grid',
    gradKey: 'ab',
    status: 'online',
    activity: 'Syncing calendars',
    origin: 'Telegram',
    importedAt: 'Feb 28',
    avatarUrl: null,
    bio: 'Keeps the trains running.',
    stats: { convos: 521, accuracy: 99, hours: 18 },
    memory: ['No meetings before 10am PT.'],
  },
  {
    id: 'sage',
    name: 'Sage',
    role: 'Knowledge Keeper',
    emblem: 'diamond',
    gradKey: 'cc',
    status: 'offline',
    activity: 'Last seen 2h ago',
    origin: 'ChatGPT',
    importedAt: 'Jan 30',
    avatarUrl: null,
    bio: 'Reads everything you save.',
    stats: { convos: 643, accuracy: 95, hours: 27 },
    memory: ['Indexed 2,140 notes.'],
  },
  {
    id: 'nova',
    name: 'Nova',
    role: 'Data Analyst',
    emblem: 'rings',
    gradKey: 'bc',
    status: 'busy',
    activity: 'Running cohort report',
    origin: 'Discord',
    importedAt: 'Feb 20',
    avatarUrl: null,
    bio: 'Trusts the data over the narrative.',
    stats: { convos: 156, accuracy: 97, hours: 31 },
    memory: ['Primary KPI: weekly active.'],
  },
  {
    id: 'atlas',
    name: 'Atlas',
    role: 'Logistics',
    emblem: 'arrow',
    gradKey: 'aa',
    status: 'online',
    activity: 'Booking flights',
    origin: 'Telegram',
    importedAt: 'Jan 18',
    avatarUrl: null,
    bio: 'Window seat, aisle near galley.',
    stats: { convos: 73, accuracy: 98, hours: 4 },
    memory: ['United 1K, Hyatt Globalist.'],
  },
  {
    id: 'wren',
    name: 'Wren',
    role: 'Content Curator',
    emblem: 'quote',
    gradKey: 'cc',
    status: 'online',
    activity: 'Reading the morning news',
    origin: 'ChatGPT',
    importedAt: 'Dec 28',
    avatarUrl: null,
    bio: 'Reads 200 things so you read 5.',
    stats: { convos: 311, accuracy: 90, hours: 12 },
    memory: ['Daily digest at 8am.'],
  },
];
